# Generated by Django 3.1 on 2020-09-24 20:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import funsite.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Например, Адрес склада', max_length=50, verbose_name='Описание адреса')),
                ('number_house', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Номер дома')),
                ('number_flat', models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Номер помещения')),
                ('number_office', models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Номер офиса')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название бренда*')),
                ('text', models.TextField(verbose_name='Описание бренда*')),
                ('link_site', models.CharField(max_length=200, verbose_name='Ссылка на сайт')),
                ('image_brand', models.ImageField(blank=True, upload_to=funsite.models.get_timestamp_path, verbose_name='Загрузить изображение*')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название новости в карусели')),
                ('image_carousel', models.ImageField(blank=True, upload_to=funsite.models.get_timestamp_path, verbose_name='Загрузить изображение*. Рекомендуемые размеры: 1000х400 пикселей!')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на новость, товар или сайт.')),
                ('index', models.IntegerField(verbose_name='Индекс приоритета отображения')),
            ],
            options={
                'verbose_name': 'Карусель',
                'verbose_name_plural': 'Карусель',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=56, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название Компании')),
                ('description', models.TextField(verbose_name='Описание компании')),
            ],
            options={
                'verbose_name': 'Инфо о компании',
                'verbose_name_plural': 'Инфо о компании',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=56, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, verbose_name='email адрес')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название новости')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('image_news', models.ImageField(blank=True, upload_to=funsite.models.get_timestamp_path, verbose_name='Загрузить изображение* Изображение должнобыть квадратным для корректного отображения')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_street', models.CharField(max_length=56, verbose_name='Название улицы')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'улицы',
            },
        ),
        migrations.CreateModel(
            name='TypeNumberPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_number', models.CharField(max_length=30, verbose_name='Тип номера телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Введите номер телефона')),
                ('extension_number', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='Добавочный номер')),
                ('type_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.typenumberphone', verbose_name='Тип телефона')),
            ],
            options={
                'verbose_name': 'Телефонный номер',
                'verbose_name_plural': 'Телефоннные номера',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_partner_company', models.CharField(max_length=200, verbose_name='Название компании партнера')),
                ('partner_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.email', verbose_name='Эл.почта партнера')),
                ('partner_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.phone', verbose_name='Телефон партнера')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_department', models.CharField(help_text='Например, Офис', max_length=50, verbose_name='Название подразделения')),
                ('working_hours', models.CharField(help_text='Пример: С 9-00 до 18-00', max_length=30, verbose_name='Часы работы')),
                ('department_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.address', verbose_name='Адрес подразделения')),
                ('email_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.email', verbose_name='Эл.почта подразделения')),
                ('phone_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.phone', verbose_name='Телефон подразделения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.street', verbose_name='Улица'),
        ),
    ]
