# Generated by Django 3.1 on 2020-08-30 08:17

from django.db import migrations, models
import funsite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название бренда')),
                ('text', models.TextField(verbose_name='Описание бренда')),
                ('image_brand', models.ImageField(blank=True, upload_to=funsite.models.get_timestamp_path, verbose_name='Загрузить изображение')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
    ]
