# Generated by Django 3.1 on 2020-09-28 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адрес'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Электронная почта', 'verbose_name_plural': 'Электронная почта'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': 'Улица', 'verbose_name_plural': 'Улица'},
        ),
        migrations.AlterModelOptions(
            name='typenumberphone',
            options={'verbose_name': 'Тип номера', 'verbose_name_plural': 'Тип номера'},
        ),
        migrations.AlterField(
            model_name='phone',
            name='extension_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='Добавочный номер'),
        ),
        migrations.AlterField(
            model_name='street',
            name='name_street',
            field=models.CharField(help_text='Если в списке нет улицы, то внесите ее нажав на "+"', max_length=56, verbose_name='Название улицы'),
        ),
        migrations.AlterField(
            model_name='typenumberphone',
            name='type_number',
            field=models.CharField(help_text='Например, Рабочий.', max_length=30, verbose_name='Тип номера телефона'),
        ),
    ]
