# Generated by Django 3.1 on 2020-09-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0002_auto_20200928_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.address', verbose_name='Адрес партнера'),
        ),
    ]
