# Generated by Django 3.1 on 2020-09-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0002_brand_link_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='link_site',
            field=models.CharField(default=True, max_length=200, verbose_name='Ссылка на сайт'),
        ),
    ]
