# Generated by Django 3.1 on 2020-09-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0003_auto_20200904_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='link_site',
            field=models.CharField(max_length=200, verbose_name='Ссылка на сайт'),
        ),
    ]
