# Generated by Django 3.1 on 2020-09-28 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0004_auto_20200928_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionInMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например, "Интегратор"', max_length=100, verbose_name='Позиция на рынке')),
            ],
            options={
                'verbose_name': 'Позиция на рынке',
                'verbose_name_plural': 'Позиция на рынке',
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='position_partner_on_market',
            field=models.ForeignKey(help_text='Например, "Интегратор"', null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.positioninmarket', verbose_name='Позиция на рынке'),
        ),
    ]
