# Generated by Django 3.1 on 2020-09-28 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0005_auto_20200928_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Должность сотрудника')),
            ],
            options={
                'verbose_name': 'Должность сотрудника',
                'verbose_name_plural': 'Должность сотрудника',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('address_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.address', verbose_name='Адрес сотрудника')),
                ('email_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.email', verbose_name='Эл.почта сотрудника')),
                ('employee_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.employeeposition', verbose_name='Должность сотрудника')),
                ('name_partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.partner', verbose_name='Принадлежность сотрудника к партнеру')),
                ('phone_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.phone', verbose_name='Номер телефона сотрудника')),
            ],
            options={
                'verbose_name': 'Фамилия',
                'verbose_name_plural': 'Фамилия',
            },
        ),
    ]
