# Generated by Django 3.1 on 2020-09-29 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0006_employee_employeeposition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='department',
            name='published_on_page',
            field=models.BooleanField(default=False, verbose_name='Публиковать информацию о подразделении на странице?'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='index',
            field=models.IntegerField(help_text='Введите число от 0 до 10. 0 имеет самый высокий приоритет.', verbose_name='Индекс приоритета отображения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.partner', verbose_name='Работает в компании'),
        ),
    ]
