# Generated by Django 3.1 on 2020-09-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0007_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Карусель', 'verbose_name_plural': 'Карусель'},
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='text',
        ),
    ]
