# Generated by Django 3.1 on 2020-10-01 20:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0007_auto_20200929_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.city', verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number_flat',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Номер помещения'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number_house',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number_office',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Номер офиса'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.street', verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='department',
            name='published_on_page',
            field=models.BooleanField(default=False, help_text='Публиковать информацию о подразделении на странице?', verbose_name='Опубликовано'),
        ),
    ]
