# Generated by Django 3.1 on 2020-10-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0008_auto_20201001_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='email_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_dep', to='funsite.email', verbose_name='Эл.почта подразделения'),
        ),
    ]
