# Generated by Django 3.1 on 2020-09-12 15:47

from django.db import migrations, models
import funsite.models


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0008_auto_20200906_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название Компании')),
                ('description', models.TextField(verbose_name='Описание компании')),
            ],
            options={
                'verbose_name': 'Инфо о компании',
                'verbose_name_plural': 'Инфо о компании',
            },
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image_carousel',
            field=models.ImageField(blank=True, upload_to=funsite.models.get_timestamp_path, verbose_name='Загрузить изображение*. Рекомендуемые размеры: 1000х400 пикселей!'),
        ),
    ]
