# Generated by Django 3.1 on 2020-10-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0009_auto_20201002_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='email_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.email', verbose_name='Эл.почта подразделения'),
        ),
    ]
