# Generated by Django 3.1 on 2020-09-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0010_auto_20200921_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='number_office',
        ),
    ]
