# Generated by Django 3.1 on 2020-10-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0010_auto_20201002_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='access_map_link',
            field=models.SlugField(blank=True, null=True, verbose_name='Ссылка на схему проезда'),
        ),
    ]
