# Generated by Django 3.1 on 2020-09-21 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0011_remove_address_number_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number_office',
            field=models.PositiveSmallIntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Номер офиса'),
            preserve_default=False,
        ),
    ]
