# Generated by Django 3.1 on 2020-09-24 18:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0011_auto_20200921_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_partner_company', models.CharField(max_length=200, verbose_name='Название компании партнера')),
            ],
        ),
        migrations.CreateModel(
            name='TypeNumberPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_number', models.CharField(max_length=30, verbose_name='Тип номера телефона')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(blank=True, help_text='Например, Адрес склада', max_length=50, verbose_name='Описание адреса'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_department',
            field=models.CharField(help_text='Например, Офис', max_length=50, verbose_name='Название подразделения'),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Введите номер телефона')),
                ('extension_number', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)], verbose_name='Добавочный номер')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.partner', verbose_name='Партнер')),
                ('type_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.typenumberphone', verbose_name='Тип телефона')),
            ],
            options={
                'verbose_name': 'Телефонный номер',
                'verbose_name_plural': 'Телефоннные номера',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, verbose_name='email адрес')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.department', verbose_name='Название подразделения')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.partner', verbose_name='Партнер')),
            ],
        ),
    ]
