# Generated by Django 3.1 on 2020-10-15 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0011_address_access_map_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='target_registration',
        ),
        migrations.AddField(
            model_name='targetregistrationpartner',
            name='target_registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.partner', verbose_name='Цель регистрации'),
        ),
        migrations.AlterField(
            model_name='address',
            name='access_map_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на схему проезда'),
        ),
    ]
