# Generated by Django 3.1 on 2020-10-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0012_auto_20201015_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetregistrationpartner',
            name='target_registration',
        ),
        migrations.AddField(
            model_name='partner',
            name='target_registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.targetregistrationpartner', verbose_name='Цель регистрации'),
        ),
    ]
