# Generated by Django 3.1 on 2020-10-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0013_auto_20201015_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='type_number',
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_partner_company',
            field=models.CharField(max_length=200, verbose_name='Название вашей компании'),
        ),
        migrations.DeleteModel(
            name='TypeNumberPhone',
        ),
    ]
