# Generated by Django 3.1 on 2020-10-19 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0014_auto_20201017_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.address', verbose_name='Адрес сотрудника'),
        ),
        migrations.AlterField(
            model_name='targetregistrationpartner',
            name='title',
            field=models.CharField(help_text='Например, покупка товаров оптом.', max_length=100, verbose_name='Цель заявки'),
        ),
    ]
