# Generated by Django 3.1 on 2020-10-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0015_auto_20201019_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.email', verbose_name='Эл.почта партнера'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.phone', verbose_name='Телефон партнера'),
        ),
    ]
