# Generated by Django 3.1 on 2020-10-19 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0016_auto_20201019_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targetregistrationpartner',
            options={'verbose_name': 'Цель заявки', 'verbose_name_plural': 'Цели заявки'},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='partner_address',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='partner_email',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='partner_phone',
        ),
    ]
