# Generated by Django 3.1 on 2020-10-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0019_mailtosupport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailtosupport',
            options={'verbose_name': 'Письмо в техподдержку', 'verbose_name_plural': 'Письма в техподдержку'},
        ),
        migrations.AddField(
            model_name='mailtosupport',
            name='equipment_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование оборудования'),
        ),
        migrations.AlterField(
            model_name='mailtosupport',
            name='message',
            field=models.TextField(verbose_name='Детально опишите вашу проблему'),
        ),
    ]
