# Generated by Django 3.1 on 2020-10-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0021_mailtosupport_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='mailtosupport',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='mailtosupport',
            name='serial_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Серийный номер оборудования'),
        ),
    ]
