# Generated by Django 3.1 on 2020-10-25 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0022_auto_20201025_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtosupport',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funsite.email', verbose_name='Ваш email для ответа'),
        ),
    ]
