# Generated by Django 3.1 on 2020-10-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0023_auto_20201025_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtosupport',
            name='sender',
            field=models.EmailField(max_length=150, verbose_name='Ваш email для ответа'),
        ),
    ]
