# Generated by Django 3.1 on 2020-10-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0024_auto_20201025_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='target_registration',
            field=models.CharField(help_text='Например, покупка товаров оптом.', max_length=100, verbose_name='Цель заявки'),
        ),
    ]
