# Generated by Django 3.1 on 2020-10-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0025_auto_20201027_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='position_partner_on_market',
            field=models.CharField(help_text='Например, "Интегратор"', max_length=100, verbose_name='Позиция на рынке'),
        ),
    ]
