# Generated by Django 3.1 on 2020-10-27 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0026_auto_20201027_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name_partner',
        ),
        migrations.AddField(
            model_name='partner',
            name='name_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.employee', verbose_name='Сотрудник'),
        ),
    ]
