# Generated by Django 3.1 on 2020-10-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0027_auto_20201027_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='name_partner',
            new_name='name_employee',
        ),
        migrations.AlterField(
            model_name='mailtosupport',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='ФИО'),
        ),
    ]
