# Generated by Django 3.1 on 2020-10-29 21:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0028_auto_20201027_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessMapLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_map_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на схему проезда')),
            ],
            options={
                'verbose_name': 'Ссылка на схему',
                'verbose_name_plural': 'Ссылки на схемы',
            },
        ),
        migrations.CreateModel(
            name='NumberHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_house', models.CharField(blank=True, help_text='Если в списке нет номера дома, то внесите нажав на "+"', max_length=6, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9/]+$')], verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Номер дома',
                'verbose_name_plural': 'Номера домов',
            },
        ),
        migrations.CreateModel(
            name='NumberOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_office', models.CharField(blank=True, help_text='Если в списке нет номера офиса, то внесите нажав на "+"', max_length=6, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9/]+$')], verbose_name='Номер офиса')),
            ],
            options={
                'verbose_name': 'Номер офиса',
                'verbose_name_plural': 'Номера офисов',
            },
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': 'Улица', 'verbose_name_plural': 'Улицы'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address_employee',
        ),
        migrations.AddField(
            model_name='department',
            name='department_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.city', verbose_name='Город подразделения'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.country', verbose_name='Страна подразделения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='employee',
            name='country_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='street',
            name='name_street',
            field=models.CharField(blank=True, help_text='Если в списке нет улицы, то внесите ее нажав на "+"', max_length=56, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Zа-яА-Я0-9]+$')], verbose_name='Название улицы'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='department',
            name='department_access_map_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.accessmaplink', verbose_name='Ссылка на схему проезда'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_number_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.numberhouse', verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_number_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.numberoffice', verbose_name='Номер офиса'),
        ),
    ]
