# Generated by Django 3.1 on 2020-10-29 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funsite', '0030_auto_20201030_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='name_employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='name_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funsite.partner', verbose_name='Компания партнер'),
        ),
    ]
